# Generated by Django 4.2.5 on 2023-09-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0002_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
