# Generated by Django 4.2.5 on 2023-09-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0003_alter_book_isbn_alter_book_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
