# Generated by Django 4.2.5 on 2023-09-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0004_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
