# Generated by Django 4.2.5 on 2023-09-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0005_alter_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
