# Generated by Django 4.2.5 on 2023-09-13 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0006_book_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page',
        ),
    ]
