# Generated by Django 4.2.5 on 2023-09-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0007_remove_book_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
