# Generated by Django 4.2.5 on 2023-09-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0008_alter_book_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
    ]
