# Generated by Django 4.2.5 on 2023-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0009_remove_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
