# Generated by Django 4.2.5 on 2023-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_apps', '0010_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
